name: Socials
version: '${project.version}'
main: dev.michaelh.socials.Socials
authors: [ MichaelHayden ]
website: michael-h.dev

commands:
  discord:
    description: "Get the Discord invite link."
    usage: "/discord"
  forums:
    description: "Get the Forum link."
    aliases: [ forum ]
    usage: "/forums"
  vote:
    description: "Get the Website link."
    usage: "/website"
  socialsreload:
    description: "Reload Socials Config"
    usage: "/socialsreload"
